### ISSUE TITLE
Is Cake.Sonar suppose to work on a Mac ? 

### ISSUE THREAD

**Issue by donnib** [AgileArchitect/Cake.Sonar#42] opened 2018-02-01 08:14 UTC

**Comment by tomstaijen** [comment] 2018-02-06 18:41
It depends on the sonarqube scanner for msbuild for that.
It's starting the scanner, but I'm getting an error "Process returned exit code 255". 
Can't find any details on that exit code anywhere.

Will dig a little further.

**Comment by tomstaijen** [comment] 2018-02-06 22:56
It's caused by https://github.com/AgileArchitect/MSBuild.SonarQube.Runner.Tool/issues/8

**Comment by tomstaijen** [comment] 2018-02-06 23:08
Works for me now after that issues is solved.
Make sure you delete the tools/MSBuild.SonarQube.Runner.Tool.4.0.2/ so that it installs the fix.

Closing this now.
Feel free to reopen if you have other issues.

**Closed by tomstaijen** 2018-02-06 23:08 UTC
