### ISSUE TITLE
Could not load tools\Addins\Cake.Sonar.1.1.1\lib\netstandard2.0\Cake.Sonar.dll (missing netstandard...)

### ISSUE THREAD

**Issue by egherrmann** [AgileArchitect/Cake.Sonar#69] opened 2018-07-05 18:53 UTC
Using Cake.Sonar v1.1.1 from PowerShell I'm getting an error saying:
    ```Could not load D:\example\tools\Addins\Cake.Sonar.1.1.1\lib\netstandard2.0\Cake.Sonar.dll (missing netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)```

When I pin to the v1.1.0 version of the addin it works correctly. This happens in multiple environments using multiple Windows, PowerShell and .NET versions.

Repro steps:

1. git clone git@github.com:cake-build/example.git
2. Replace contents of build.cake with the example from https://github.com/AgileArchitect/Cake.Sonar/blob/master/README.md
3. Run SonarBegin
    ```
    PS D:\example> .\build.ps1 -Target SonarBegin
    Preparing to run build script...
    Running build script...
    Could not load D:\example\tools\Addins\Cake.Sonar.1.1.1\lib\netstandard2.0\Cake.Sonar.dll (missing netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
    D:/example/build.cake(12,6): error CS0103: The name 'SonarBegin' does not exist in the current context
    D:/example/build.cake(12,21): error CS0246: The type or namespace name 'SonarBeginSettings' could not be found (are you missing a using directive or an assembly reference?)
    D:/example/build.cake(22,6): error CS0103: The name 'SonarEnd' does not exist in the current context
    D:/example/build.cake(22,19): error CS0246: The type or namespace name 'SonarEndSettings' could not be found (are you missing a using directive or an assembly reference?)
    Error: Error(s) occurred when compiling build script:
    D:/example/build.cake(12,6): error CS0103: The name 'SonarBegin' does not exist in the current context
    D:/example/build.cake(12,21): error CS0246: The type or namespace name 'SonarBeginSettings' could not be found (are you missing a using directive or an assembly reference?)
    D:/example/build.cake(22,6): error CS0103: The name 'SonarEnd' does not exist in the current context
    D:/example/build.cake(22,19): error CS0246: The type or namespace name 'SonarEndSettings' could not be found (are you missing a using directive or an assembly reference?)
    ```

I was able to fix this by installing .NET Framework 4.7.2 Runtime. I wanted to open an Issue to bring it to your attention and in case others are searching for a solution.

**Comment by raghav710** [comment] 2018-07-06 12:19
we faced the exact issue yesterday when using the v1.1.1
Pinning to v1.1.0 fixed it for us.
Environments: Windows machine and a Windows docker image
It has the .NET Core 2.1 SDK installed.

**Comment by tomstaijen** [comment] 2018-07-11 20:43
I'm not able to reproduce because i don't have access to a windows machine with .NET < 4.6.1, but i think the issue is exactly that: using a .net version below what netstandard2.0 supports. So i'll add net46 again (which is what Cake supports) and that might fix it.

**Comment by raghav710** [comment] 2018-07-18 09:57
@tomstaijen I'll verify the new changes and confirm

**Comment by tomstaijen** [comment] 2018-10-18 04:33
Closing this for now. Can reopen if issue is confirmed to still exist.

**Closed by tomstaijen** 2018-10-18 04:33 UTC
